# Generated by Django 4.0 on 2023-03-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ImageField(upload_to='images'),
        ),
    ]
