# Generated by Django 4.0 on 2023-03-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail_img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
