# Generated by Django 4.0 on 2023-03-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_file_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
