# Generated by Django 4.0 on 2023-03-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products_product',
        ),
    ]
