# Generated by Django 4.0 on 2023-03-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_photos_alter_product_thumbnail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_img',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
