# Generated by Django 4.0 on 2023-04-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_photos_alter_product_thumbnail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='pc', max_length=1000),
        ),
    ]
